name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run ng build -- --prod --base-href /KniffelKalk/

      - name: Deploy to GitHub Pages
        run: npx ngh --dir=dist/kniffelkalk --message="Deploy to GitHub Pages" --branch=gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
